### ISSUE TITLE
Problem with my vimrc on server

### ISSUE THREAD

**Issue by mariaortiz0401** [mariaortiz0401/HRDAG-dotfiles#1]
Hi, @vm-wylbur, @thegargiulian 
I just got to clone this repo in our server (using ssh key) and I could link the bashrc file on server with the one in my repository. I just had one problem with fasd (command not found) but everything else was ok

So, my questions here are:

**1.** What do I do with this _command not found_? I think I don't have enough permissions to install it so, what's the right solution here?
**2.** I created a .vimrc on $HOME and I linked it to the one on my repository. Sadly, changes didn't reflect on my vim ;_;
    I ran :version and I can see the "real" file is `system vimrc file: "$VIM/sysinit.vim" ` and if I run :scriptnames I can't see a vimrc   config file. What can I do now?

3. For pluggins, I run this 
 `curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`

   And also I created a plugged directory on .vim directory.

   My question here is: is it ok to do this manually? O there is a config on vim or bashrc to do this Plugin Config. I remembered you didn't do this on our meeting, so I wanna know which step I'm missing here or if you did it and I didn't see it 

Thank you so much for your help!

**Comment by vm-wylbur** [comment]
hi @mariaortiz0401 , 

1) for software that we should install at the system level, just let me know and I'll install it. `fasd` should work now. 

2) which version of vim are you really running? **vim** or NeoVim with **nvim**? If you're using NeoVim (and I recommend that you do), you should be using `~/.config/nvim/init.vim` as your initialization file, not `~/.vimrc`. So make your symlink to the `init.vim` and let me know how it goes.

3) Yes, it's good to run the Plug setup manually. However, if you're using NeoVim, you should use this command:
```
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
```

Note that NeoVim has [slightly different setup files](https://wiki.archlinux.org/index.php/Neovim) than vim. Read through this link and let me know what questions you have.

**Comment by mariaortiz0401** [comment]
Ah, ok, I'm using vim. So I will read about nvim and will modify my vimrc a little bit before doing the symlink on the server. 
I will let you know how it goes
Thank you so much! :smile:

**Comment by mariaortiz0401** [comment]
@jgduenasl

**Comment by mariaortiz0401** [comment]
Hi, @vm-wylbur 
I modified my vimrc a little bit (just the directory for plugin installation) and I did my symlink to ~/.config/nvim/init.vim and everything worked fine!
Also, I pushed this change on my server, created the .config folder and nvim folder, made the curl, and finally I made the symlink and all worked too! 
Thank you so much for your help

I just have another question: what is the alias you guys used to make vim command = nvim ?

**Comment by vm-wylbur** [comment]
Wonderful news! Congratulations. Please close this issue when you're done. 

When you install NeoVim, the `nvim` alias is automatically added. If you say `nvim` on sirvjnr, you'll get NeoVim, and I am sure that happens under other kinds of linux too. I have a little more work to do with it (you can run `:CheckHealth` inside NeoVim to see what's left).
